### ISSUE TITLE
Error in AndroidManifest.xml

### ISSUE THREAD

**Issue by mx5jon** [TreeFrogApps/MultiProcessPreferences#1]
I'm getting the following error in Android Studio, when I modify the AndroidManifest.xml file:
 Unresolved class MultiProvider.
for android:name

Here is part of what is in the AndroidManifest.xml

  <application
        android:allowBackup="true"
        android:icon="@mipmap/clock"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <provider
            android:authorities="eurotimesystems.multi_preferences.MultiProvider"
            android:name=".multi_preferences.MultiProvider" <---This is the line that gives the error.
            android:process=":multi_preferences"
            android:exported="false"/>

Here is what I've got in MultiProvider.java, MultiPreferences.java,  and PreferenceInteractor.java
package com.eurotimesystems.multi_preferences;

In MultiProvider.java 
I've set the PROVIDER_NAME to:
private static final String PROVIDER_NAME =
            "com.eurotimesystems.multi_preferences.MultiProvider";

**Comment by TreeFrogApps** [comment]
this is now not an issue - you got passed this and posted issue#2?
